package common.storedClasses.annotations;

import java.lang.annotation.*;

/**
 * indicates that field is generated automatically
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface AutoGenerated {
}
